---
title: "R code for Risk measure (logistic part)"
output:
  html_document:
    df_print: paged
---

```{r message=FALSE}
library(psycho)
library(tidyverse)
library(dplyr)

library(glmnet)
library(pROC)
library(ggplot2)
library(Metrics)
```

## read data and standardization
```{r}
dat <-
  read.csv("../data/SME_dataset.csv")
input_x <- as.matrix(dat)
input_x <- input_x[, -c(1, 2)]
input_x_std <- input_x %>%
  as_tibble(.) %>%
  mutate_all(., scale) %>% as.matrix(.)
```

## separate companies into 2 clusters
```{r}
comp_str <- c(
  "../result/connect_flag_df_threshold_0.1.csv",
  "../result/connect_flag_df_threshold_0.05.csv"
)
c_str <- c("0.1 gamma C", "0.05 gamma C")
nc_str <- c("0.1 gamma NC", "0.05 gamma NC")
correlatedComp <- comp_str %>%
  map(., ~ read.csv(.)) %>%
  setNames(c_str)
repNum <- function(x) {
  x_cf <- x$connect_flag
  y <- seq(1, length(x_cf))
  z <- map2(.x = x_cf, .y = y, (function(x, y) {
    if (x == 1) {
      y
    } else {
      0
    }
  }))
  z <- z[z != 0]
  return(z)
}
correlatedCompNo <-
  correlatedComp %>% map(., ~ repNum(.) %>% unlist(.))
unCorrelatedCompNo <-
  map2(.x = correlatedCompNo, .y = correlatedComp, ~ seq(1, length(.y$connect_flag))[-.x]) %>% setNames(nc_str)
allSample <- list(seq(1, dim(dat)[1])) %>% setNames("all sample")
allInput <- c(correlatedCompNo, unCorrelatedCompNo, allSample)
```

## Sample allocation
```{r}
X_test_num <-
  map2(.x = allInput,
       .y = allInput,
       ~ sample(.x, length(.y) * 3 /
                  10 %>% round()))
X_test <- X_test_num %>% map(., ~ input_x[c(.),])
Y_test <- map(X_test_num, ~ dat$status[c(.)])
X_all_num <- map(.x = allInput, ~ sample(.x))
X_all <- X_all_num %>% map(., ~ input_x[c(.),])
Y_all <- map(X_all_num, ~ dat$status[c(.)])
X_train_num <-
  map2(.x = X_test_num, .y = X_all_num, ~ setdiff(.y, .x) %>% sample())
X_train <- X_train_num %>% map(., ~ input_x[c(.),])
Y_train <- map(X_train_num, ~ dat$status[c(.)])
```

## Lasso
```{r}
lasso_reg <- map2(
  .x = X_train,
  .y = Y_train,
  ~ cv.glmnet(
    .x,
    .y,
    family = "binomial",
    type.measure = "mse",
    intercept = FALSE
  )
)
lasso_coef <- map(lasso_reg, ~ coef(., s = "lambda.min"))
lasso_predict <- map2(.x = lasso_reg,
                      .y = X_test,
                      ~ predict(.x, .y, type = "response", s = "lambda.min"))
cbdList <- function(x) {
  cbdName <- c("0.1 gamma", "0.05 gamma", "all sample")
  z <-
    list(c(x[[1]], x[[3]]), c(x[[2]], x[[4]]), x[[5]]) %>% setNames(cbdName)
  return(z)
}
Y_test_cbd <- cbdList(Y_test)

lasso_predict_cbd <- cbdList(lasso_predict)
lasso_roc <-
  map2(.x = lasso_predict_cbd, .y = Y_test_cbd, ~ roc(.y, .x))
lasso_roc
```

## elastic-Net
```{r}
ela_reg <- map2(
  .x = X_train,
  .y = Y_train,
  ~ cv.glmnet(
    .x,
    .y,
    alpha = 0.5,
    family = "binomial",
    type.measure = "mse",
    intercept = FALSE
  )
)
ela_coef <- map(ela_reg, ~ coef(., s = "lambda.min"))
ela_predict <- map2(.x = ela_reg,
                    .y = X_test,
                    ~ predict(.x, .y, type = "response", s = "lambda.min"))
ela_predict_cbd <- cbdList(ela_predict)
ela_roc <-
  map2(.x = ela_predict_cbd, .y = Y_test_cbd, ~ roc(.y, .x))
ela_roc
```

## adaptive lasso
```{r}
ridge_reg <- map2(
  .x = X_train,
  .y = Y_train,
  ~ cv.glmnet(
    .x,
    .y,
    alpha = 0,
    family = "binomial",
    type.measure = "mse",
    intercept = FALSE
  )
)
ridge_coef <- map(ridge_reg, ~ coef(., s = "lambda.min")) %>%
  map(., as.numeric) %>%
  map(., abs) %>% map(., ~ `^`(.x, 2))
XY_train <-
  map2(.x = X_train, .y = Y_train, ~ list(.x, .y)) %>% map(., ~ setNames(., c("X", "Y")))
ada_lasso_reg <- map2(
  .x = XY_train,
  .y = ridge_coef,
  ~ cv.glmnet(
    .x[[1]],
    .x[[2]],
    penalty.factor = 1 / .y,
    family = "binomial",
    type.measure = "mse",
    intercept = FALSE
  )
)
ada_lasso_coef <- map(ada_lasso_reg, ~ coef(., s = "lambda.min"))
ada_lasso_predict <- map2(.x = ada_lasso_reg,
                          .y = X_test,
                          ~ predict(.x, .y, type = "response", s = "lambda.min"))
ada_lasso_predict_cbd <- cbdList(ada_lasso_predict)
ada_lasso_roc <-
  map2(.x = ada_lasso_predict_cbd, .y = Y_test_cbd, ~ roc(.y, .x))
ada_lasso_roc
```

## adaptive elastic-Net
```{r}
ada_ela_reg <- map2(
  .x = XY_train,
  .y = ridge_coef,
  ~ cv.glmnet(
    .x[[1]],
    .x[[2]],
    alpha = 0.5,
    penalty.factor = 1 / .y,
    family = "binomial",
    type.measure = "mse",
    intercept = FALSE
  )
)
ada_ela_coef <- map(ada_ela_reg, ~ coef(., s = "lambda.min"))
ada_ela_predict <- map2(.x = ada_ela_reg,
                        .y = X_test,
                        ~ predict(.x, .y, type = "response", s = "lambda.min"))
ada_ela_predict_cbd <- cbdList(ada_ela_predict)
ada_ela_roc <-
  map2(.x = ada_ela_predict_cbd, .y = Y_test_cbd, ~ roc(.y, .x))
ada_ela_roc
```

```{r include=FALSE}
multiplot <-
  function(...,
           plotlist = NULL,
           file,
           cols = 1,
           layout = NULL) {
    library(grid)
    plots <- c(list(...), plotlist)
    numPlots <- length(plots)
    if (is.null(layout)) {
      layout <- matrix(seq(1, cols * ceiling(numPlots / cols)),
                       ncol = cols,
                       nrow = ceiling(numPlots / cols))
    }
    if (numPlots == 1) {
      print(plots[[1]])
    } else {
      grid.newpage()
      pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))
      
      for (i in 1:numPlots) {
        matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))
        
        print(plots[[i]],
              vp = viewport(
                layout.pos.row = matchidx$row,
                layout.pos.col = matchidx$col
              ))
      }
    }
  }
```


## Combine results
```{r,fig.width=10}
allName <- c(c_str, nc_str, "all sample")
lasso_coef <-
  lasso_coef %>% setNames(., map(allName, ~ paste(., ".lasso")))
ela_coef <-
  ela_coef %>% setNames(., map(allName, ~ paste(., ".ela")))
ada_lasso_coef <-
  ada_lasso_coef %>% setNames(., map(allName, ~ paste(., ".ada_lasso")))
ada_ela_coef <-
  ada_ela_coef %>% setNames(., map(allName, ~ paste(., ".ada_ela")))
all_coef <- c(lasso_coef, ela_coef, ada_lasso_coef, ada_ela_coef)
allName <- names(all_coef)
all_coef_dfr <- all_coef %>%
  map(., as.matrix %>% as.data.frame()) %>%
  (function(x) {
    do.call(cbind, x)
  })
names(all_coef_dfr) <- allName
all_coef_dfr[abs(all_coef_dfr) < 0.001] = 0
all_coef_dfr

g1 <-
  ggroc(lasso_roc, legacy.axes = T) + xlab("FPR") + ylab("TPR") + ggtitle("Lasso") + geom_segment(aes(
    x = 0,
    xend = 1,
    y = 0,
    yend = 1
  ),
  color = "darkgrey",
  linetype = "dashed")
g2 <-
  ggroc(ela_roc, legacy.axes = T) + xlab("FPR") + ylab("TPR") + ggtitle("Elastic-Net") +
  geom_segment(aes(
    x = 0,
    xend = 1,
    y = 0,
    yend = 1
  ),
  color = "darkgrey",
  linetype = "dashed")
g3 <-
  ggroc(ada_lasso_roc, legacy.axes = T) + xlab("FPR") + ylab("TPR") + ggtitle("Adaptive lasso") +
  geom_segment(aes(
    x = 0,
    xend = 1,
    y = 0,
    yend = 1
  ),
  color = "darkgrey",
  linetype = "dashed")
g4 <-
  ggroc(ada_ela_roc, legacy.axes = T) + xlab("FPR") + ylab("TPR") + ggtitle("Adaptive Elastic-Net") +
  geom_segment(aes(
    x = 0,
    xend = 1,
    y = 0,
    yend = 1
  ),
  color = "darkgrey",
  linetype = "dashed")

multiplot(g1, g2, g3, g4, cols = 2)
```

## ROC
```{r paged.print=TRUE}
roc_all = list(
  roc.test(lasso_roc[[3]], lasso_roc[[1]]),
  roc.test(lasso_roc[[3]], lasso_roc[[2]]),
  roc.test(ada_lasso_roc[[3]], ada_lasso_roc[[1]]),
  roc.test(ada_lasso_roc[[3]], ada_lasso_roc[[2]]),
  roc.test(ela_roc[[3]], ela_roc[[1]]),
  roc.test(ela_roc[[3]], ela_roc[[2]]),
  roc.test(ada_ela_roc[[3]], ada_ela_roc[[1]]),
  roc.test(ada_ela_roc[[3]], ada_ela_roc[[2]])
)
roc_stat = roc_all %>% map(.,  ~ cbind(.x$statistic, .x$p.value)) %>% (function(x) {
  do.call(rbind, x)
})
rownames(roc_stat) = c(
  'lasso 0.1',
  'lasso 0.05',
  'ada lasso 0.1',
  'ada lasso 0.05',
  'ela 0.1',
  'ela 0.05',
  'ada ela 0.1',
  'ada ela 0.05'
)
colnames(roc_stat) = c('statistic', 'p-value')
roc_stat %>% as.data.frame()

# show auc results
auc_list = list(lasso_roc, ela_roc, ada_lasso_roc, ada_ela_roc) %>% map(.,  ~
                                                                          map(.,  ~ .x$auc) %>% unlist) %>% (function(x) {
                                                                            do.call(cbind, x)
                                                                          })
colnames(auc_list) = c('lasso', 'elastic net', 'adaptive lasso', 'adaptive elastic net')
auc_list %>% as.data.frame()
```

